### ISSUE TITLE
Missing code under :root selector

### ISSUE THREAD

**Issue by QuantumInformation** [sebastian-software/postcss-smart-import#43]
Input:
```css
/**
 This doesn't promise to conform to any framework but I like to use it in my own projects.
 I based it off of the framework I know best, bootstrap 3

 It is designed to be used with the sizes as the min point at which the size classifican applies. Ie at 481px screen width, it would be "small". There is no extra
 small class below 480px as it is the default application at 479px and below
 */

:root {
  --small: 480px;
  --medium: 768px;
  --large: 992px;
  --xlarge: 1200px;
}
p.fo{
  padding: 0;
}
```
output

![image](https://cloud.githubusercontent.com/assets/216566/21897543/cd63653a-d8e1-11e6-99e4-ca254190e2aa.png)
